### ISSUE TITLE
Ты и и гру у меня спиздил?

### ISSUE THREAD

**Issue by devlysh** [Sekhno/game-of-life#1]
Ты вообще о**ел? :) Ты мною чтоли прикидываешься?

**Comment by Sekhno** [comment]
Ты только по названию сравнивал? Там же другая игра

**Comment by devlysh** [comment]
Структура директорий, зависимостей и утилит идентичная.

Но ты копию моего сайта и CV удали главное, а то я по поводу DMCA не шутил.

**Comment by devlysh** [comment]
Или ты хочешь сказать «там другой сайт» и «там другое сиви»? лол

**Comment by devlysh** [comment]
please delete this issue
